// scripts/build-tokens.ts
// design/tokens.json (W3C DTCG) -> src/app/globals.css @theme sentinel block.
// Contract: specs/012-shadcn-design-system/contracts/token-pipeline.md

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(SCRIPT_DIR, "..");
const TOKENS_PATH = resolve(REPO_ROOT, "design/tokens.json");
const CSS_PATH = resolve(REPO_ROOT, "src/app/globals.css");

const BEGIN_MARKER = "/* BEGIN:tokens";
const END_MARKER = "/* END:tokens */";
const GENERATED_HEADER =
  "  /* BEGIN:tokens (generated by scripts/build-tokens.ts from design/tokens.json. Edit tokens.json, not here.) */";

const REQUIRED_CATEGORIES = ["color", "radius", "shadow"];

type DtcgNode = { [key: string]: unknown };

function isLeaf(node: unknown): node is { $value: unknown } {
  return typeof node === "object" && node !== null && "$value" in node;
}

function flatten(node: unknown, prefix: string[], out: Record<string, string>): void {
  if (isLeaf(node)) {
    out[prefix.join("-")] = String(node.$value);
    return;
  }
  if (typeof node !== "object" || node === null) return;
  for (const [k, v] of Object.entries(node as DtcgNode)) {
    if (k.startsWith("$") || k.startsWith("_")) continue;
    flatten(v, prefix.concat(k), out);
  }
}

function fail(msg: string): never {
  process.stderr.write("ERROR: " + msg + "\n");
  process.exit(1);
}

function main(): void {
  if (!existsSync(TOKENS_PATH)) fail("design tokens missing at " + TOKENS_PATH);

  let raw: string;
  try {
    raw = readFileSync(TOKENS_PATH, "utf8");
  } catch (e) {
    return fail("failed to read " + TOKENS_PATH + ": " + (e as Error).message);
  }

  let parsed: DtcgNode;
  try {
    parsed = JSON.parse(raw);
  } catch (e) {
    return fail("tokens.json is not valid JSON: " + (e as Error).message);
  }

  for (const cat of REQUIRED_CATEGORIES) {
    if (!(cat in parsed)) fail('required category "' + cat + '" missing');
  }

  const flat: Record<string, string> = {};
  for (const [cat, node] of Object.entries(parsed)) {
    if (cat.startsWith("$") || cat.startsWith("_")) continue;
    flatten(node, [cat], flat);
  }
  if (Object.keys(flat).length === 0) fail("no tokens flattened; unexpected structure.");

  if (!existsSync(CSS_PATH)) fail("globals.css missing at " + CSS_PATH);
  const css = readFileSync(CSS_PATH, "utf8");

  const beginIdx = css.indexOf(BEGIN_MARKER);
  const endIdx = css.indexOf(END_MARKER);
  if (beginIdx === -1 || endIdx === -1 || endIdx < beginIdx) {
    fail("sentinel markers not found (expected " + BEGIN_MARKER + "..." + END_MARKER + ")");
  }

  const lineStart = css.lastIndexOf("\n", beginIdx) + 1;
  const lineEnd = css.indexOf("\n", endIdx);
  if (lineEnd === -1) fail("END:tokens line malformed");

  const vars = Object.keys(flat).sort().map((k) => "  --" + k + ": " + flat[k] + ";");
  const newBlock = [GENERATED_HEADER].concat(vars, ["  " + END_MARKER]).join("\n");
  const next = css.slice(0, lineStart) + newBlock + css.slice(lineEnd);

  if (next === css) {
    process.stdout.write("tokens:build — idempotent (" + Object.keys(flat).length + " vars, no change)\n");
    return;
  }

  writeFileSync(CSS_PATH, next, "utf8");
  const delta = next.length - css.length;
  const sign = delta >= 0 ? "+" : "";
  process.stdout.write("tokens:build — wrote " + Object.keys(flat).length + " vars (" + sign + delta + " bytes)\n");
}

main();
